name: Logseq Publish apply Tenset theme
description: inserts logseq-tenset-theme to published site
runs:
  using: composite
  steps:
    - name: Set up Node
      uses: actions/setup-node@v3
    - name: Check out logseq-tenset-theme repo
      uses: actions/checkout@v4
      with:
        repository: tenset-security/logseq-tenset-theme
        path: logseq-tenset-theme
    - run: npm --prefix ${{ github.workspace }}/logseq-tenset-theme i
      shell: bash
    - run: npm --prefix ${{ github.workspace }}/logseq-tenset-theme run build
      shell: bash
    - run: find | grep www
      shell: bash
    - run: cp ${{ github.workspace }}/logseq-tenset-theme/build/tenset-theme.css ${{ github.workspace }}/www/static/css/custom.css
      shell: bash
    - run: mkdir ${{ github.workspace }}/logseq/fonts
      shell: bash
    - run: cp ${{ github.workspace }}/logseq-tenset-theme/build/*.ttf ${{ github.workspace }}/www/static/css/fonts/
      shell: bash